### ISSUE TITLE
Not working on Magento 1.9.2.2

### ISSUE THREAD

**Issue by blopa** [elgentos/AutoInvoice#1]
Hi, how are you?

I'm glad I found this extension, I was really looking for a solution like this, and it's free. So, thank you.

But I can't make it to work with Magento 1.9.2.2. I can install the extension and configure my conditions to create an invoice, but it isn't working. 

My config:

http://i.imgur.com/AhsZ27E.png

Thank you

**Comment by peterjaap** [comment]
There is no state/status combination with Processed/Shipped. Please read up on state/statuses and try again;

http://ka.lpe.sh/2012/04/21/magento-order-state-vs-status/
http://stackoverflow.com/questions/9627354/what-is-the-difference-between-state-and-status-column-in-table-sales-flat-o
http://www.magestore.com/manage-magento-online-store/magento-order-status-and-magento-order-state
